# Generated by Django 3.1.6 on 2021-03-01 23:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('count', models.SmallIntegerField(default=1, verbose_name='Кол-во')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment_photo', verbose_name='Изображение элемента')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=16, verbose_name='№/метка')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('photo_map', models.ImageField(blank=True, null=True, upload_to='location_photo', verbose_name='Изображение кабинета на плане')),
                ('url_coord', models.URLField(blank=True, null=True, verbose_name='Ссылка на координаты')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_manufacturer', models.CharField(max_length=255, verbose_name='Название от производителя')),
                ('manufacturer', models.CharField(max_length=255, null=True, verbose_name='Производитель')),
                ('url_site', models.URLField(blank=True, null=True, verbose_name='Ссылка на web-страницу')),
                ('name_bookkeeping', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование от бухгалтерии')),
                ('inventory_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Инвентарный номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена (руб)')),
                ('count', models.SmallIntegerField(default=1, verbose_name='Общее кол-во')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='thing_photo', verbose_name='Изображение предмета')),
                ('photo_base_location', models.ImageField(blank=True, null=True, upload_to='thing_photo_location', verbose_name='Фотография метонахождения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('base_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc_thing', to='storage.location', verbose_name='Местоположение/кабинет')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UseThings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(default=1, verbose_name='Количество')),
                ('justification', models.TextField(blank=True, null=True, verbose_name='Обоснование')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Базовое местоположение')),
                ('created', models.DateField(default=datetime.date.today)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_employee', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_thing', to='storage.thing', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Использование',
                'verbose_name_plural': 'Использование',
            },
        ),
        migrations.AddField(
            model_name='thing',
            name='employees',
            field=models.ManyToManyField(through='storage.UseThings', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='thing',
            name='finresp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finresp_thing', to=settings.AUTH_USER_MODEL, verbose_name='Материально-ответственное лицо'),
        ),
        migrations.CreateModel(
            name='StatusEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('count', models.SmallIntegerField(default=1, verbose_name='Кол-во')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_equipment', to='storage.equipment', verbose_name='Элемент')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thing_equipment', to='storage.thing', verbose_name='Позиция'),
        ),
    ]
