# Generated by Django 3.1.6 on 2021-03-03 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='count',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='thing',
        ),
        migrations.AddField(
            model_name='equipment',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.CreateModel(
            name='CompositionEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(default=1, verbose_name='Кол-во')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copmpos_equipment', to='storage.equipment', verbose_name='Элемент')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compos_thing', to='storage.thing', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Состав',
                'verbose_name_plural': 'Составы',
            },
        ),
        migrations.AddField(
            model_name='thing',
            name='equipments',
            field=models.ManyToManyField(through='storage.CompositionEquipment', to='storage.Equipment', verbose_name='Сотрудники'),
        ),
    ]
