# Generated by Django 3.1.6 on 2021-03-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210317_2123'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='location',
        ),
        migrations.RemoveField(
            model_name='usething',
            name='location',
        ),
        migrations.AddField(
            model_name='thing',
            name='loc_cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thing', to='storage.cabinet', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='thing',
            name='loc_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание местоположения'),
        ),
        migrations.AddField(
            model_name='thing',
            name='loc_photo',
            field=models.ImageField(blank=True, null=True, upload_to='location_photo', verbose_name='Фотография местоположения'),
        ),
        migrations.AddField(
            model_name='usething',
            name='loc_cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use', to='storage.cabinet', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='usething',
            name='loc_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание местоположения'),
        ),
        migrations.AddField(
            model_name='usething',
            name='loc_photo',
            field=models.ImageField(blank=True, null=True, upload_to='location_photo', verbose_name='Фотография местоположения'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
