# Generated by Django 3.1.6 on 2021-02-15 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='name_bookkeeping',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование от бухгалтерии'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='photo_base_location',
            field=models.ImageField(blank=True, null=True, upload_to='thing_photo_location', verbose_name='Фотография метонахождения'),
        ),
        migrations.CreateModel(
            name='StatusEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус')),
                ('note', models.CharField(max_length=255, verbose_name='Примечание')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('count', models.SmallIntegerField(default=1, verbose_name='Кол-во')),
                ('status', models.ManyToManyField(to='storage.StatusEquipment', verbose_name='Статусы')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thing_equipment', to='storage.thing', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
    ]
