# Generated by Django 3.1.6 on 2021-03-15 17:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20210315_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='inventory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Инвентарный номер'),
        ),
    ]
