# Generated by Django 3.1.6 on 2021-02-15 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0002_auto_20210215_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusequipment',
            name='count',
            field=models.SmallIntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.ManyToManyField(blank=True, to='storage.StatusEquipment', verbose_name='Статусы'),
        ),
        migrations.AlterField(
            model_name='statusequipment',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='statusequipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
