# Generated by Django 3.1.6 on 2021-02-15 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0003_auto_20210215_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='finresp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finresp_thing', to=settings.AUTH_USER_MODEL, verbose_name='Материально-ответственное лицо'),
        ),
    ]
