# Generated by Django 3.1.6 on 2021-03-15 18:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20210315_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusthing',
            name='inventory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Инвентарные номера'),
        ),
        migrations.AddField(
            model_name='thing',
            name='is_accounting',
            field=models.BooleanField(default=0, verbose_name='Бухгалтерский учёт'),
        ),
        migrations.AddField(
            model_name='thing',
            name='is_set',
            field=models.BooleanField(default=0, verbose_name='Набор'),
        ),
        migrations.AddField(
            model_name='usething',
            name='inventory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Инвентарные номера'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='inventory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Инвентарные номера'),
        ),
    ]
