# Generated by Django 3.1.6 on 2021-02-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_thing_finresp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usethings',
            name='status',
        ),
    ]
