# Generated by Django 3.1.6 on 2021-03-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20210315_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusthing',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='usething',
            name='inventory',
        ),
        migrations.AlterField(
            model_name='thing',
            name='inventory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инвентарные номера'),
        ),
    ]
