# Generated by Django 3.1.6 on 2021-02-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_remove_usethings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_photo', verbose_name='Изображение элемента'),
        ),
    ]
