# Generated by Django 3.1.6 on 2021-03-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20210316_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thing', to='storage.location', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='thing_photo', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='thing_picture', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='usething',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use', to='storage.location', verbose_name='Местоположение'),
        ),
    ]
