# Generated by Django 3.1.6 on 2021-02-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_equipment_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='status',
        ),
        migrations.AddField(
            model_name='statusequipment',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_equipment', to='storage.equipment', verbose_name='Элемент'),
            preserve_default=False,
        ),
    ]
