# Generated by Django 3.1.6 on 2021-03-16 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20210316_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipment',
            new_name='Composition',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='equipments',
        ),
        migrations.AddField(
            model_name='thing',
            name='composition',
            field=models.ManyToManyField(through='storage.Composition', to='storage.Thing', verbose_name='Элементы'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thing', to='storage.location', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='usething',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use', to='storage.location', verbose_name='Местоположение'),
        ),
    ]
