# Generated by Django 3.1.6 on 2021-03-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20210317_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='status_picture', verbose_name='Картинка'),
        ),
    ]
