# Generated by Django 3.1.6 on 2021-03-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_status_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={'ordering': ['thing'], 'verbose_name': 'Состав', 'verbose_name_plural': 'Составы'},
        ),
        migrations.AlterModelOptions(
            name='statusthing',
            options={'verbose_name': 'Присвоение статусов', 'verbose_name_plural': 'Присвоение статусов'},
        ),
        migrations.AlterModelOptions(
            name='usething',
            options={'verbose_name': 'Использование предметов', 'verbose_name_plural': 'Использование предметов'},
        ),
        migrations.AddField(
            model_name='thing',
            name='is_consumable',
            field=models.BooleanField(default=False, verbose_name='Расходный материал'),
        ),
    ]
