# Generated by Django 3.1.6 on 2021-03-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20210317_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='is_consumable',
            new_name='is_material',
        ),
    ]
