# Generated by Django 3.1.6 on 2021-03-17 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0010_auto_20210317_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thing_person', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник'),
        ),
    ]
