# Generated by Django 3.1.6 on 2021-04-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_ib', models.PositiveIntegerField(verbose_name='Год обучения в IB')),
                ('year_rus', models.PositiveIntegerField(verbose_name='Год обучения в РФ')),
            ],
            options={
                'verbose_name': 'Год обучения',
                'verbose_name_plural': 'Года обучения',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('A', 'Критерий A'), ('B', 'Критерий B'), ('C', 'Критерий C'), ('D', 'Критерий D')], default='A', max_length=1)),
                ('name_eng', models.CharField(max_length=32, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=32, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'Критерий оценивания',
                'verbose_name_plural': 'Критерии оценивания',
            },
        ),
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=3, verbose_name='Аббревиатура')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
            ],
            options={
                'verbose_name': 'IB Программа',
                'verbose_name_plural': 'IB Программы',
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=32, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=32, null=True, verbose_name='Название на рус. языке')),
                ('programm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_group', to='sumassess.programm', verbose_name='Программа IB')),
            ],
            options={
                'verbose_name': 'Предметная группа IB',
                'verbose_name_plural': 'Предметные группы IB',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=32, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=32, null=True, verbose_name='Название на рус. языке')),
                ('ibgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='sumassess.subjectgroup', verbose_name='Предметная группа')),
            ],
            options={
                'verbose_name': 'Учебная дисциплина',
                'verbose_name_plural': 'Учебные дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Абсолютный номер')),
                ('letter', models.PositiveIntegerField(choices=[(1, 'i'), (2, 'ii'), (3, 'iii'), (4, 'iv')], default=1, verbose_name='Метка в критерии')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('shortname_eng', models.CharField(max_length=32, verbose_name='Краткое название на англ. языке')),
                ('shortname_rus', models.CharField(blank=True, max_length=32, null=True, verbose_name='Краткое название на рус. языке')),
                ('criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strand', to='sumassess.criteria', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Стрэнд',
                'verbose_name_plural': 'Стрэнды',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.TextField(null=True, verbose_name='Описание на англ. языке')),
                ('name_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
                ('strand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective', to='sumassess.strand', verbose_name='Стрэнд')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective', to='sumassess.classyear', verbose_name='Год обучения в IB')),
            ],
            options={
                'verbose_name': 'Образовательная цель',
                'verbose_name_plural': 'Образовательные цели',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.TextField(null=True, verbose_name='Описание на англ. языке')),
                ('name_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
                ('objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='sumassess.objective', verbose_name='Образовательная цель')),
            ],
            options={
                'verbose_name': 'Уровень достижений',
                'verbose_name_plural': 'Уровни достижений',
            },
        ),
        migrations.AddField(
            model_name='criteria',
            name='ibgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria', to='sumassess.subjectgroup', verbose_name='Предметная группа'),
        ),
        migrations.AddField(
            model_name='classyear',
            name='programm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_year', to='sumassess.programm', verbose_name='Программа IB'),
        ),
    ]
