# Generated by Django 3.1.6 on 2021-02-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('A', 'Критерий A'), ('B', 'Критерий B'), ('C', 'Критерий C'), ('D', 'Критерий D')], default='A', max_length=1)),
                ('name', models.CharField(max_length=30, verbose_name='Название критерия на английском')),
                ('name_rus', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название критерия на русском')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
                'ordering': ['subject', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название предметной области')),
                ('name_rus', models.CharField(max_length=30, verbose_name='Название на русском')),
                ('programm', models.CharField(choices=[('PYP', 'Primary Years Programme'), ('MYP', 'Middle Years Programme'), ('DP', 'Diploma Programme')], default='MYP', max_length=3)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['programm', 'name'],
            },
        ),
        migrations.CreateModel(
            name='YearIB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_ib', models.CharField(max_length=2, verbose_name='Год обучения в IB')),
                ('programm', models.CharField(choices=[('PYP', 'Primary Years Programme'), ('MYP', 'Middle Years Programme'), ('DP', 'Diploma Programme')], default='MYP', max_length=3)),
                ('grade_rus', models.CharField(max_length=2, verbose_name='Год обучения в РФ')),
            ],
            options={
                'verbose_name': 'Год IB',
                'verbose_name_plural': 'Года IB',
                'ordering': ['programm', 'year_ib'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(choices=[('1', 'i'), ('2', 'ii'), ('3', 'iii'), ('4', 'iv')], default='A', max_length=1)),
                ('name', models.TextField(blank=True, null=True)),
                ('name_rus', models.TextField(blank=True, null=True)),
                ('criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sumassess.criteria')),
                ('year_ib', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sumassess.yearib')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ['strand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('name_rus', models.TextField(blank=True, null=True)),
                ('point', models.PositiveIntegerField(default=0)),
                ('objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sumassess.objective')),
            ],
            options={
                'verbose_name': 'Уровень достижений',
                'verbose_name_plural': 'Уровни достижений',
                'ordering': ['point', 'name'],
            },
        ),
        migrations.AddField(
            model_name='criteria',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sumassess.subject'),
        ),
    ]
