# Generated by Django 3.1.6 on 2021-02-28 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_a', models.SmallIntegerField(default=0, verbose_name='Оценка по критерию A')),
                ('mark_b', models.SmallIntegerField(default=0, verbose_name='Оценка по критерию B')),
                ('mark_c', models.SmallIntegerField(default=0, verbose_name='Оценка по критерию C')),
                ('mark_d', models.SmallIntegerField(default=0, verbose_name='Оценка по критерию D')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Журнал оценивания',
                'verbose_name_plural': 'Журналы оцениваний',
                'ordering': ['unit', 'student'],
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('A', 'Критерий A'), ('B', 'Критерий B'), ('C', 'Критерий C'), ('D', 'Критерий D')], default='A', max_length=1)),
                ('name', models.CharField(max_length=255, verbose_name='Название критерия на английском')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название критерия на русском')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
                'ordering': ['subject', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_dnevnik', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID класса из Дневник.РУ')),
                ('letter', models.CharField(default='A', max_length=1, verbose_name='Буква класса')),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['year', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Название цели на английском')),
                ('name_rus', models.TextField(blank=True, null=True, verbose_name='Название цели на русском')),
                ('criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objective_cri', to='sumassess.criteria', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ['year_ib', 'criteria', 'strand'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название периода')),
                ('data_start', models.DateField(null=True, verbose_name='Дата начала периода')),
                ('data_end', models.DateField(null=True, verbose_name='Дата окончания периода')),
                ('id_dnevnik', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID системы Дневник.РУ')),
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды',
                'ordering': ['data_start'],
            },
        ),
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='Учебный год')),
                ('data_start', models.DateField(null=True, verbose_name='Дата начала учебного года')),
                ('data_end', models.DateField(null=True, verbose_name='Дата окончания учебного года')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебный года',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название предмета')),
                ('id_dnevnik', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID системы Дневник.РУ')),
            ],
            options={
                'verbose_name': 'Учебный предмет',
                'verbose_name_plural': 'Учебные предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название предметной области')),
                ('name_rus', models.CharField(max_length=30, verbose_name='Название на русском')),
                ('programm', models.CharField(choices=[('PYP', 'Primary Years Programme'), ('MYP', 'Middle Years Programme'), ('DP', 'Diploma Programme')], default='MYP', max_length=3)),
            ],
            options={
                'verbose_name': 'Предметная область',
                'verbose_name_plural': 'Предметные области',
                'ordering': ['programm', 'name'],
            },
        ),
        migrations.CreateModel(
            name='YearIB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_ib', models.CharField(max_length=2, verbose_name='Год обучения в IB')),
                ('programm', models.CharField(choices=[('PYP', 'Primary Years Programme'), ('MYP', 'Middle Years Programme'), ('DP', 'Diploma Programme')], default='MYP', max_length=3)),
                ('grade_rus', models.CharField(max_length=2, verbose_name='Год обучения в РФ')),
            ],
            options={
                'verbose_name': 'Год IB',
                'verbose_name_plural': 'Года IB',
                'ordering': ['programm', 'year_ib'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название юнита')),
                ('objective', models.ManyToManyField(blank=True, related_name='unit_objective', to='sumassess.Objective', verbose_name='Выбранные цели')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_period', to='sumassess.period', verbose_name='Период')),
                ('styear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_styear', to='sumassess.studyyear', verbose_name='Учебный год')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_subject', to='sumassess.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
                ('year_ib', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_year', to='sumassess.yearib', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Юнит',
                'verbose_name_plural': 'Юниты',
                'ordering': ['year_ib', 'period', 'subject'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='subjgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_sg', to='sumassess.subjectgroup'),
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Направление подгруппы')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroup_group', to='sumassess.group', verbose_name='Класс')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroup_subject', to='sumassess.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroup_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Подгруппа',
                'verbose_name_plural': 'Подгруппы',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=12, null=True, verbose_name='Сокращённое имя')),
                ('surname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя')),
                ('id_dnevnik', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID системы Дневник.РУ')),
                ('gender', models.CharField(blank=True, choices=[('М', 'мужской'), ('Ж', 'женский')], max_length=1, null=True, verbose_name='Пол')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_group', to='sumassess.group', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['group', 'shortname'],
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=2, verbose_name='Номер')),
                ('letter', models.CharField(max_length=3, verbose_name='Буквенное обозначение')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название стрэнда на английском')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название стрэнда на русском')),
                ('shortname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое название стрэнда на английском')),
                ('shortname_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое название стрэнда на русском')),
                ('criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strand_cri', to='sumassess.criteria', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Cтрэнд',
                'verbose_name_plural': 'Стрэнды',
                'ordering': ['id', 'letter', 'name'],
            },
        ),
        migrations.AddField(
            model_name='period',
            name='styear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_year', to='sumassess.studyyear', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='objective',
            name='strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective_strand', to='sumassess.strand', verbose_name='Стрэнд'),
        ),
        migrations.AddField(
            model_name='objective',
            name='year_ib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objective_year', to='sumassess.yearib', verbose_name='Год'),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Название уровня на английском')),
                ('name_rus', models.TextField(blank=True, null=True, verbose_name='Название уровня на русском')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
                ('objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_objective', to='sumassess.objective', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Уровень достижений',
                'verbose_name_plural': 'Уровни достижений',
                'ordering': ['objective', 'point', 'name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='styear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_styear', to='sumassess.studyyear', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_year', to='sumassess.yearib', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria_sub', to='sumassess.subjectgroup'),
        ),
        migrations.CreateModel(
            name='AssessmentUnitLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('assessmentunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aul_assessuint', to='sumassess.assessmentunit', verbose_name='Журнал юнита')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aul_level', to='sumassess.level', verbose_name='Уровень достижений')),
            ],
            options={
                'verbose_name': 'Выбор уровня',
                'verbose_name_plural': 'Выборы уровней',
                'ordering': ['assessmentunit', 'level'],
            },
        ),
        migrations.AddField(
            model_name='assessmentunit',
            name='level',
            field=models.ManyToManyField(blank=True, related_name='assessment_level', through='sumassess.AssessmentUnitLevel', to='sumassess.Level', verbose_name='Выбранные уровни достижений'),
        ),
        migrations.AddField(
            model_name='assessmentunit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_student', to='sumassess.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='assessmentunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_unit', to='sumassess.unit', verbose_name='Юнит'),
        ),
    ]
