# Generated by Django 3.1.6 on 2021-02-15 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sumassess', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['objective', 'point', 'name'], 'verbose_name': 'Уровень достижений', 'verbose_name_plural': 'Уровни достижений'},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['year_ib', 'criteria', 'strand'], 'verbose_name': 'Цель', 'verbose_name_plural': 'Цели'},
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название юнита')),
                ('objective', models.ManyToManyField(to='sumassess.Objective', verbose_name='Выбранные цели')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sumassess.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_unit', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
                ('year_ib', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sumassess.yearib')),
            ],
            options={
                'verbose_name': 'Юнит',
                'verbose_name_plural': 'Юниты',
                'ordering': ['year_ib', 'subject', 'name'],
            },
        ),
    ]
