# Generated by Django 3.1.6 on 2021-04-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classyear',
            name='year_ib',
            field=models.CharField(max_length=32, null=True, verbose_name='Год обучения в IB'),
        ),
    ]
