# Generated by Django 3.1.6 on 2021-02-16 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sumassess', '0002_auto_20210216_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(default='A', max_length=1, verbose_name='Буква класса')),
                ('cl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='sumassess.yearib', verbose_name='Год обучения')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['cl', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=1, verbose_name='Номер')),
                ('letter', models.CharField(max_length=3, verbose_name='Буквенное обозначение')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название стрэнда на английском')),
                ('name_rus', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название стрэнда на русском')),
            ],
            options={
                'verbose_name': 'Cтрэнд',
                'verbose_name_plural': 'Стрэнды',
                'ordering': ['num', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['year_ib', 'name'], 'verbose_name': 'Юнит', 'verbose_name_plural': 'Юниты'},
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Название уровня на английском'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name_rus',
            field=models.TextField(blank=True, null=True, verbose_name='Название уровня на русском'),
        ),
        migrations.AlterField(
            model_name='level',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sumassess.objective', verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='level',
            name='point',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sumassess.criteria', verbose_name='Критерий'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Название цели на английском'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='name_rus',
            field=models.TextField(blank=True, null=True, verbose_name='Название цели на русском'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='year_ib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sumassess.yearib', verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sumassess.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='year_ib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sumassess.yearib', verbose_name='Год'),
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Направление подгруппы')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroup_group', to='sumassess.group', verbose_name='Класс')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroup_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Подгруппа',
                'verbose_name_plural': 'Подгруппы',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=40, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='Имя')),
                ('id_dnevnik', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID системы Дневник.РУ')),
                ('gender', models.CharField(choices=[('М', 'мужской'), ('Ж', 'женский')], default='М', max_length=1, verbose_name='Пол')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sumassess.group', verbose_name='Класс')),
                ('subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sumassess.subgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_ib', models.SmallIntegerField(default=0, verbose_name='Итоговая оценка IB')),
                ('level', models.ManyToManyField(blank=True, to='sumassess.Level', verbose_name='Выбранные уровни достижений')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_student', to='sumassess.student', verbose_name='Студент')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_unit', to='sumassess.unit', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Журнал оценивания',
                'verbose_name_plural': 'Журналы оцениваний',
                'ordering': ['unit', 'student'],
            },
        ),
        migrations.AlterField(
            model_name='objective',
            name='strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sumassess.strand', verbose_name='Стрэнд'),
        ),
    ]
