# Generated by Django 3.1.6 on 2021-04-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0003_auto_20210405_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteria',
            options={'ordering': ['ibgroup', 'letter'], 'verbose_name': 'Критерий оценивания', 'verbose_name_plural': 'Критерии оценивания'},
        ),
        migrations.AlterField(
            model_name='strand',
            name='shortname_eng',
            field=models.CharField(max_length=64, verbose_name='Краткое название на англ. языке'),
        ),
        migrations.AlterField(
            model_name='strand',
            name='shortname_rus',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Краткое название на рус. языке'),
        ),
    ]
