# Generated by Django 3.1.6 on 2021-02-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0004_auto_20210216_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название критерия на английском'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='name_rus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название критерия на русском'),
        ),
        migrations.AlterField(
            model_name='strand',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название стрэнда на английском'),
        ),
        migrations.AlterField(
            model_name='strand',
            name='name_rus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название стрэнда на русском'),
        ),
    ]
