# Generated by Django 3.1.6 on 2021-04-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0005_auto_20210405_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['objective', 'point'], 'verbose_name': 'Уровень достижений', 'verbose_name_plural': 'Уровни достижений'},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['year', 'strand'], 'verbose_name': 'Образовательная цель', 'verbose_name_plural': 'Образовательные цели'},
        ),
        migrations.AddField(
            model_name='level',
            name='point',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы'),
        ),
    ]
