# Generated by Django 3.1.6 on 2021-02-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0005_auto_20210216_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strand',
            name='num',
            field=models.CharField(max_length=2, verbose_name='Номер'),
        ),
    ]
