# Generated by Django 3.1.6 on 2021-04-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0006_auto_20210405_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgroup',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='subjectgroup_pic', verbose_name='Картинка'),
        ),
    ]
