# Generated by Django 3.1.6 on 2021-02-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0006_auto_20210216_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='strand',
            name='shortname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое название стрэнда на английском'),
        ),
        migrations.AddField(
            model_name='strand',
            name='shortname_rus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое название стрэнда на русском'),
        ),
    ]
