# Generated by Django 3.1.6 on 2021-04-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0007_subjectgroup_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='criteria_pic', verbose_name='Картинка'),
        ),
    ]
