# Generated by Django 3.1.6 on 2021-02-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0007_auto_20210216_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='Учебный год')),
            ],
        ),
        migrations.AlterModelOptions(
            name='strand',
            options={'ordering': ['num', 'letter', 'name'], 'verbose_name': 'Cтрэнд', 'verbose_name_plural': 'Стрэнды'},
        ),
        migrations.AddField(
            model_name='group',
            name='styear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_styear', to='sumassess.studyyear', verbose_name='Учебный год'),
        ),
    ]
