# Generated by Django 3.1.6 on 2021-02-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0008_auto_20210216_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyyear',
            options={'ordering': ['year'], 'verbose_name': 'Учебный год', 'verbose_name_plural': 'Учебный года'},
        ),
        migrations.AddField(
            model_name='group',
            name='group_dnevnik',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ID класса из Дневник.РУ'),
        ),
    ]
