# Generated by Django 3.1.6 on 2021-04-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0008_criteria_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgroup',
            name='schema',
            field=models.ImageField(blank=True, null=True, upload_to='subjectgroup_schema', verbose_name='Схема'),
        ),
    ]
