# Generated by Django 3.1.6 on 2021-02-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0009_auto_20210216_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название предметной области')),
                ('name_rus', models.CharField(max_length=30, verbose_name='Название на русском')),
                ('programm', models.CharField(choices=[('PYP', 'Primary Years Programme'), ('MYP', 'Middle Years Programme'), ('DP', 'Diploma Programme')], default='MYP', max_length=3)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['programm', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name_rus',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='programm',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название предмета'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subjgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_sg', to='sumassess.subjectgroup'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria_sub', to='sumassess.subjectgroup'),
        ),
    ]
