# Generated by Django 3.1.6 on 2021-04-28 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sumassess', '0010_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='level',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sumassess.objective', verbose_name='Образовательная цель'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=140, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='student',
            name='shortname',
            field=models.CharField(max_length=140, verbose_name='Скрытое имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
