# Generated by Django 3.1.6 on 2021-02-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0011_auto_20210216_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['surname', 'name', 'shortname'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AddField(
            model_name='student',
            name='shortname',
            field=models.CharField(max_length=12, null=True, verbose_name='Сокращённое имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='student',
            name='subgroup',
            field=models.ManyToManyField(blank=True, to='sumassess.SubGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия'),
        ),
    ]
