# Generated by Django 3.1.6 on 2021-02-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0012_auto_20210217_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyyear',
            name='data_end',
            field=models.DateField(null=True, verbose_name='Дата окончания учебного года'),
        ),
        migrations.AddField(
            model_name='studyyear',
            name='data_start',
            field=models.DateField(null=True, verbose_name='Дата начала учебного года'),
        ),
    ]
