# Generated by Django 3.1.6 on 2021-02-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0013_auto_20210217_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strand',
            options={'ordering': ['id', 'letter', 'name'], 'verbose_name': 'Cтрэнд', 'verbose_name_plural': 'Стрэнды'},
        ),
        migrations.AlterField(
            model_name='assessmentunit',
            name='level',
            field=models.ManyToManyField(blank=True, related_name='assessment_level', to='sumassess.Level', verbose_name='Выбранные уровни достижений'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='objective',
            field=models.ManyToManyField(blank=True, to='sumassess.Objective', verbose_name='Выбранные цели'),
        ),
    ]
