# Generated by Django 3.1.6 on 2021-02-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0014_auto_20210217_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='subgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_subgroup', to='sumassess.subgroup', verbose_name='Подгруппа'),
        ),
    ]
