# Generated by Django 3.1.6 on 2021-02-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0015_unit_subgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='subgroup',
        ),
    ]
