# Generated by Django 3.1.6 on 2021-02-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0017_unit_trimester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['year_ib', 'trimester'], 'verbose_name': 'Юнит', 'verbose_name_plural': 'Юниты'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='student',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sumassess.subgroup', verbose_name='Группа'),
        ),
    ]
