# Generated by Django 3.1.6 on 2021-02-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0018_auto_20210217_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название юнита'),
        ),
    ]
