# Generated by Django 3.1.6 on 2021-02-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0019_auto_20210218_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subgroup',
        ),
    ]
