# Generated by Django 3.1.6 on 2021-02-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0021_auto_20210221_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['group', 'shortname'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='objective',
            field=models.ManyToManyField(blank=True, related_name='unit_objective', to='sumassess.Objective', verbose_name='Выбранные цели'),
        ),
    ]
