# Generated by Django 3.1.6 on 2021-02-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0022_auto_20210221_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentunit',
            name='mark_a',
            field=models.SmallIntegerField(default=0, verbose_name='Оценка по критерию A'),
        ),
        migrations.AddField(
            model_name='assessmentunit',
            name='mark_b',
            field=models.SmallIntegerField(default=0, verbose_name='Оценка по критерию B'),
        ),
        migrations.AddField(
            model_name='assessmentunit',
            name='mark_c',
            field=models.SmallIntegerField(default=0, verbose_name='Оценка по критерию C'),
        ),
        migrations.AddField(
            model_name='assessmentunit',
            name='mark_d',
            field=models.SmallIntegerField(default=0, verbose_name='Оценка по критерию D'),
        ),
    ]
