# Generated by Django 3.1.6 on 2021-02-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0023_auto_20210223_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentunit',
            name='mark_ib',
        ),
    ]
