# Generated by Django 3.1.6 on 2021-02-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0024_remove_assessmentunit_mark_ib'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['year_ib'], 'verbose_name': 'Юнит', 'verbose_name_plural': 'Юниты'},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='trimester',
        ),
        migrations.AddField(
            model_name='unit',
            name='styear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_styear', to='sumassess.studyyear', verbose_name='Учебный год'),
        ),
    ]
