# Generated by Django 3.1.6 on 2021-02-23 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0025_auto_20210223_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название периода')),
                ('data_start', models.DateField(null=True, verbose_name='Дата начала периода')),
                ('data_end', models.DateField(null=True, verbose_name='Дата окончания периода')),
                ('id_dnevnik', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID системы Дневник.РУ')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_period', to='sumassess.period', verbose_name='Период'),
        ),
    ]
