# Generated by Django 3.1.6 on 2021-02-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0026_auto_20210223_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['data_start'], 'verbose_name': 'Период', 'verbose_name_plural': 'Периоды'},
        ),
        migrations.AddField(
            model_name='period',
            name='styear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_year', to='sumassess.studyyear', verbose_name='Учебный год'),
        ),
    ]
