# Generated by Django 3.1.6 on 2021-02-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0027_auto_20210223_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['year_ib', 'period', 'subject'], 'verbose_name': 'Юнит', 'verbose_name_plural': 'Юниты'},
        ),
        migrations.RemoveField(
            model_name='assessmentunit',
            name='level',
        ),
        migrations.AddField(
            model_name='assessmentunit',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
    ]
