# Generated by Django 3.1.6 on 2021-02-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0028_auto_20210225_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentUnitLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('assessmentunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aul_assessuint', to='sumassess.assessmentunit', verbose_name='Журнал юнита')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aul_level', to='sumassess.level', verbose_name='Уровень достижений')),
            ],
            options={
                'verbose_name': 'Выбор уровня',
                'verbose_name_plural': 'Выборы уровней',
                'ordering': ['assessmentunit', 'level'],
            },
        ),
        migrations.AddField(
            model_name='assessmentunit',
            name='level',
            field=models.ManyToManyField(blank=True, related_name='assessment_level', through='sumassess.AssessmentUnitLevel', to='sumassess.Level', verbose_name='Выбранные уровни достижений'),
        ),
    ]
