# Generated by Django 3.1.6 on 2021-02-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumassess', '0029_auto_20210225_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='id_dnevnik',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ID системы Дневник.РУ'),
        ),
    ]
