# Generated by Django 3.1.6 on 2021-03-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ID карты пропуска'),
        ),
    ]
