# Generated by Django 3.1.6 on 2021-03-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('employee', '0002_auto_20210317_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lognotebook',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc_lognotebook', to='storage.cabinet', verbose_name='Местоположение'),
        ),
    ]
